### ISSUE TITLE
Solution Pokelist

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/pokelist-quiz-4ahif-SimonPrimetzhofer#2]
Dear Mr. Stropek!

Here is the link to my final solution:
https://rawgit.com/rstropek-teaching/pokelist-quiz-4ahif-SimonPrimetzhofer/master/index.html

I used the Bootstrap.css framework to style the list and the navigation buttons. I hope that's enough as I didn't use it for the details.

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
@SimonPrimetzhofer Thank you for your homework. I tested your app and it worked well 👍 .

Greetings,
Rainer Stropek.
